//! pass-core: store model, entry codec, and (eventually) git engine, TOTP,
//! and sync policy for pass/passage-compatible stores.
//!
//! Deliberately crypto-free. All encryption and decryption goes through the
//! [`crypto::CryptoBackend`] trait, implemented per platform (NorseHorsePGPCore /
//! AgePony engines on mobile, sequoia-openpgp / age crate on desktop).
//!
//! Ground truth for behavior is the fixture corpus generated by the real
//! `pass` and `passage` CLIs — see `docs/passage-store-semantics.md`.

pub mod crypto;
pub mod entry;
pub mod store;
pub mod totp;

/// Version of the core library, surfaced through FFI for diagnostics.
pub fn core_version() -> String {
    env!("CARGO_PKG_VERSION").to_string()
}

#[cfg(test)]
mod tests {
    #[test]
    fn version_is_nonempty() {
        assert!(!super::core_version().is_empty());
    }
}
